name: tasino
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  path_provider: ^2.0.14
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  text_to_speech: ^0.2.3
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
